### ISSUE TITLE
Challenge 1: Results Summary Component

### ISSUE THREAD

**Issue by ysmn-sl** [ysmn-sl/frontend-mentor-challenges#1]
### Description
This issue tracks the completion of the [Results Summary Component](https://www.frontendmentor.io/learning-paths/javascript-frameworks-and-libraries-JDWoqQjMyb/steps/6704d3eb5832c087f2c48604/challenge/start) challenge from Frontend Mentor. The goal is to build the results summary component according to the provided design.

### Tasks
- [x] Build the HTML structure
- [x] Style using Tailwind CSS
- [x] Make the component responsive for mobile and desktop
- [x] Add hover and focus states for interactive elements
- [x] Dynamically populate content from `data.json`
